GET http://localhost:3000/api/hello

###
POST http://localhost:3000/api/hello
Content-Type: application/json

{
  "name": "basma"
}

###
GET http://localhost:3000/api/todos

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "id":"acf44aa2-e342-482d-8f67-357f71fafdda"
}

###
PATCH http://localhost:3000/api/todos/019af4ab-6bc4-7508-88a9-e6eaa9a55c79/edit
Content-Type: application/json

{
  "title":"this todo has been edited.",
  "isCompleted":false
}

###
DELETE http://localhost:3000/api/todos/44c26879-4066-42ce-84ad-11d1d35369af
